<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>nl.tno</groupId>
	<artifactId>netn-bus</artifactId>

	<!-- Replaced in gitlab build pipeline -->
	<version>0.0.0-git</version>
	<packaging>jar</packaging>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.release>25</maven.compiler.release>

		<!-- RTI provider versions -->
		<!-- <pitch.version>6.1.3</pitch.version>
		<vtmak.version>4.6.1a</vtmak.version>
		<portico.version>2.1.3</portico.version>
		<lrcserver.version>3.1</lrcserver.version> -->
	</properties>

	<repositories>
		<repository>
			<id>gitlab-maven</id>
			<url>https://ci.tno.nl/gitlab/api/v4/groups/3562/-/packages/maven</url>
		</repository>
		<repository>
			<id>central</id>
			<url>https://repo.maven.apache.org/maven2</url>
		</repository>
	</repositories>

<!-- DONT DEPLOY YET TO GITLAB!!! -->
	<!-- <distributionManagement>
		<repository>
			<id>gitlab-maven</id>
			<url>
				https://ci.tno.nl/gitlab/api/v4/projects/${env.CI_PROJECT_ID}/packages/maven</url>
		</repository>
		<snapshotRepository>
			<id>gitlab-maven</id>
			<url>
				https://ci.tno.nl/gitlab/api/v4/projects/${env.CI_PROJECT_ID}/packages/maven</url>
		</snapshotRepository>
	</distributionManagement> -->

	<dependencies>
		<!-- Pitch RTI provider -->
		<!-- <dependency>
			<groupId>se.pitch</groupId>
			<artifactId>prti1516e</artifactId>
			<version>${pitch.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>se.pitch</groupId>
			<artifactId>prticore</artifactId>
			<version>${pitch.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>se.pitch</groupId>
			<artifactId>booster1516</artifactId>
			<version>${pitch.version}</version>
			<scope>runtime</scope>
		</dependency> -->

		<!-- Pitch FedPro Client RTI provider -->
		<!-- <dependency>
			<groupId>se.pitch</groupId>
			<artifactId>fedpro-session</artifactId>
			<version>${pitch.version}</version>
			<scope>runtime</scope>
		</dependency>		
		<dependency>
			<groupId>se.pitch</groupId>
			<artifactId>fedpro-protobuf</artifactId>
			<version>${pitch.version}</version>
			<scope>runtime</scope>
		</dependency>		
		<dependency>
			<groupId>se.pitch</groupId>
			<artifactId>fedpro-client-evolved</artifactId>
			<version>${pitch.version}</version>
			<scope>runtime</scope>
		</dependency> -->

		<!-- RTI extensions -->
		<dependency>
			<groupId>nl.tno</groupId>
			<artifactId>oorti</artifactId>
			<version>2.0.2</version>
			<type>jar</type>
		</dependency>

		<!-- FOM and helpers -->
		<dependency>
			<groupId>nl.tno</groupId>
			<artifactId>netn4</artifactId>
			<version>6.0.4</version>
			<type>jar</type>
		</dependency>

		<!-- <dependency>
			<groupId>nl.tno</groupId>
			<artifactId>geocalc</artifactId>
			<version>1.0.0</version>
			<type>jar</type>
		</dependency> -->

		<!-- JUNIT TESTING LIBARIES -->
		<!-- <dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>6.0.3</version>
			<scope>test</scope>
		</dependency> -->

	</dependencies>

	<build>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.15.0</version>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.10.0</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>

</project>
